# Generated by Django 3.2.2 on 2021-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutus_director_whatwedo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name': 'What we do', 'verbose_name_plural': 'What we do'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='about_cover',
            field=models.ImageField(null=True, upload_to='about_img/'),
        ),
        migrations.AlterField(
            model_name='whatwedo',
            name='text',
            field=models.TextField(default='', max_length=100),
        ),
    ]
