# Generated by Django 3.2.2 on 2021-05-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210508_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='embedded',
            field=models.TextField(blank=True, help_text='YouTube video or Facebook Post or Google Map (optional)', null=True),
        ),
    ]
