# Generated by Django 3.2.2 on 2021-05-08 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_news_embedded'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
