# Generated by Django 3.2.2 on 2021-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_whatwedo_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='caption',
            field=models.CharField(default='', max_length=500),
        ),
    ]
