# Generated by Django 3.2.2 on 2021-05-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_gallery_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
